# permissions for end users to view upcloudvms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vm-controller
    app.kubernetes.io/managed-by: kustomize
  name: upcloudvm-viewer-role
rules:
- apiGroups:
  - infrastructure.github.com
  resources:
  - upcloudvms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.github.com
  resources:
  - upcloudvms/status
  verbs:
  - get
